# Generated by Django 3.1.7 on 2021-04-15 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0002_blog_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 15, 32, 34, 327542, tzinfo=utc), verbose_name='Time published'),
        ),
    ]
