# Generated by Django 3.1.7 on 2021-04-15 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0003_auto_20210415_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 23, 47, 28, 171594, tzinfo=utc), verbose_name='Time published'),
        ),
    ]
